import Head from "next/head"
import React from "react"
import styles from "@/styles/page.module.css"

export default function Example() {
	return (
		<>
			<Head>
				<title>MJB Boilerplate page route example</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<h1>{"Here is another page."}</h1>
			</main>
		</>
	)
}
