import Head from "next/head"
import styles from "@/styles/page.module.css"
import { Header } from "@/components"

export default function Home() {
	return (
		<>
			<Head>
				<title>MJB Boilerplate</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<Header subTitle={"A hug-o-tron community."} />
			</main>
		</>
	)
}
