import Head from "next/head"
import styles from "@/styles/page.module.css"
import { GitHubLink, Header } from "@/components"

export default function Home() {
	return (
		<>
			<Head>
				<title>MJB Boilerplate</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<Header
					title={"🍽️ MJB Boilerplate"}
					subTitle={
						"React app quick start with Next.js, TypeScript, CSS Modules, and React Testing Library"
					}
				/>
				<footer className={styles.footer}>
					<GitHubLink link={"https://github.com/MollyJeanB/mjb-boilerplate"} />
				</footer>
			</main>
		</>
	)
}
